### PR TITLE
Corda-Account

### PR DESCRIPTION
**Pull request by zhengmar3**
Added corda account sample:

overall look: account table + account graph representation
image

Account graph is inter-active, represent the hierarchy level, eg. CBDC has Natwest, Barcalys and HSBC accounts:

image
image

### CODE REVIEW

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by zhengmar3** [comment]
image

Yeah, was thinking about label position as well. Changed to this, helps a bit for readability.

@Evgeny-Timoshin-R3

**Comment by Evgeny-Timoshin-R3** [comment]
> image
> 
> Yeah, was thinking about label position as well. Changed to this, helps a bit for readability.
> 
> @Evgeny-Timoshin-R3

Looks good! thx

**Review by yarivus — APPROVED** [review]
LGTM

**Pull request merged**
