### PR TITLE
React-query basic query usage (mutation example to be added when back-end api is ready)

### PR DESCRIPTION
**Pull request by zhengmar3**
Added basic react-query usage example: fetching data from star wars api.

**_Note:_** I was working on adding react-query mutation example as well, but after some thinking, I have decided to showcase how to do more complex queries and mutations on Corda specific pages instead. Since professional service will provide me with a "fake" api server with some dummy data. So that I can showcase how react-query interact with real back-end data.

the new commit addressing the issue:

configure notistack to be accessible from outside react component

added button to fetch data & to trigger fake fetch error

Now added global error handler on react-query client setup in app.tsx

image

### CODE REVIEW

**Review by Evgeny-Timoshin-R3 — COMMENTED** [review]
Looks good!. 

Might be worth adding some more small examples, such as:

- fetching on button click.
- dealing with an error. (show notification)
- dealing with empty data. (show notification)

**Comment by zhengmar3** [comment]
> Looks good!.
> 
> Might be worth adding some more small examples, such as:
> 
> * fetching on button click.
> * dealing with an error. (show notification)
> * dealing with empty data. (show notification)

Yeah good points.
the new commit addressing the issue:

- configure notistack to be accessible from outside react component

- added button to fetch data & to trigger fake fetch error

- Now added global error handler on react-query client setup in app.tsx

**Review by Evgeny-Timoshin-R3 — APPROVED** [review]
Looks good! thx

**Review by yarivus — APPROVED** [review]
Thanks @zhengmar3 - can you refresh the screenshot following the recent commit

**Review by conor-r3 — APPROVED** [review]

**Pull request merged**
