### PR TITLE
Data-table example

### PR DESCRIPTION
**Pull request by zhengmar3**
Very simple data-table example using MUI data-grid.

image

Added row click event + dialog/modal showing clicked row detail:
image

### CODE REVIEW

**Review by Evgeny-Timoshin-R3 — COMMENTED** [review]
Looks good. 

How about some on click examples on rows for a modal pop up with the details of that row displayed? (This will show how to manage state for a "selected row" and do stuff with it). 

Also, do you think its worth having an example of react query + table integration example? Might be nice.

**Comment by zhengmar3** [comment]
> Looks good.
> 
> Do you think its worth having an example of react query + table integration example?

Yes, I will start working on corda specific examples, which will cover the integration of react-query and table display.

**Comment by Evgeny-Timoshin-R3** [comment]
> > Looks good.
> > Do you think its worth having an example of react query + table integration example?
> 
> Yes, I will start working on corda specific examples, which will cover the integration of react-query and table display.

Nice one. 

How about on row click + modal example? (I updated my comment above but I think your replied by then :P )

**Review by Evgeny-Timoshin-R3 — APPROVED** [review]
Nice one! lgtm.

**Comment by zhengmar3** [comment]
> @zhengmar3 From the screenshots I could not see if the user would have ability to:
> 
> 1. filter results
> 2. sort results
> 3. row/column/content manipulation (e.g. add/remove etc)

For 1 and 2: Yes, the MUI data-grid components comes with built-in pagination, sorting and filtering function. Also show/hide columns.

But for row/column content manipulation no, that adding and removing are usually handled by a back-end.

**Pull request merged**
